defaults: &defaults
  facebook_fanpage: https://www.facebook.com/buyonline.DGD
  instagram_fanpage: https://www.instagram.com/buyonline.DGD
  email_contact: buyonline.dgd@gmail.com

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
